"""First migration

Revision ID: 4208f90bf3d7
Revises: 
Create Date: 2020-02-16 15:20:01.348674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4208f90bf3d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boundaries',
    sa.Column('gss_code', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('type', sa.String(length=3), nullable=True),
    sa.Column('suffix', sa.String(length=25), nullable=True),
    sa.Column('parent_id', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['boundaries.gss_code'], ),
    sa.PrimaryKeyConstraint('gss_code')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('mobile_tel', sa.String(length=13), nullable=True),
    sa.Column('post_code', sa.String(length=8), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_tel')
    )
    op.create_table('_person_boundary',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('boundary_id', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundaries.gss_code'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'boundary_id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('boundary_id', sa.String(length=9), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundaries.gss_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('boundary_code', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['boundary_code'], ['boundaries.gss_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('boundary_id', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundaries.gss_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['people.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('_person_team',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=9), nullable=False),
    sa.Column('is_contact', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'team_id')
    )
    op.create_table('_user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=10), nullable=False),
    sa.Column('value', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'setting_key')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('boundary_id', sa.String(length=9), nullable=False),
    sa.Column('team_id', sa.String(length=9), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contacts_made', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundaries.gss_code'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_event_activities',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'activity_type')
    )
    op.create_table('_event_attendance',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('did_attend', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'person_id')
    )
    op.create_table('_event_road',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.BigInteger(), nullable=False),
    sa.Column('starting_point', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'road_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_event_road')
    op.drop_table('_event_attendance')
    op.drop_table('_event_activities')
    op.drop_table('events')
    op.drop_table('_user_settings')
    op.drop_table('_person_team')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('roads')
    op.drop_table('campaigns')
    op.drop_table('_person_boundary')
    op.drop_table('people')
    op.drop_table('boundaries')
    # ### end Alembic commands ###
