"""empty message

Revision ID: 5d4d9292c909
Revises: db6baf90a076
Create Date: 2020-02-26 22:46:22.097077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4d9292c909'
down_revision = 'db6baf90a076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('people_mobile_tel_key', 'people', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('people_mobile_tel_key', 'people', ['mobile_tel'])
    # ### end Alembic commands ###
