"""empty message

Revision ID: db6baf90a076
Revises: 4208f90bf3d7
Create Date: 2020-02-22 12:02:00.298643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6baf90a076'
down_revision = '4208f90bf3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_boundary_types',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('consent',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('obtained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('consent_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'key')
    )
    op.add_column('boundaries', sa.Column('type_code', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'boundaries', '_boundary_types', ['type_code'], ['code'])
    op.drop_column('boundaries', 'type')
    op.drop_column('boundaries', 'suffix')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boundaries', sa.Column('suffix', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.add_column('boundaries', sa.Column('type', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'boundaries', type_='foreignkey')
    op.drop_column('boundaries', 'type_code')
    op.drop_table('consent')
    op.drop_table('_boundary_types')
    # ### end Alembic commands ###
